name: 'ci'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm test
